version: '3'

services:
  db:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/redis

  api:
    depends_on:
      - "db"
    build: ./thumbnailAnnotator.parent/thumbnailAnnotator.api/
    ports:
      - "8081:8081"
    dns:
      - 8.8.8.8
      - 9.9.9.9
  webapp:
    depends_on:
      - "api"
      - "db"
    build: ./app
    ports:
      - "8080:80"
    

volumes:
  redis_data:
    driver: local
