##
# Example run: 
#  make sure to docker-compose pull to get the latest images!
#  API_PORT=10310 APP_PORT=10311 docker-compose up --build -d
#
##
version: '3'

services:
  db:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ${PWD}/redis_data:/bitnami/redis/data

  api:
    depends_on:
      - "db"
    image: 'uhhlt/nlp_thumbnailannotator_api:latest'
    ports:
      - "${API_PORT}:8081"
  app:
    depends_on:
      - "api"
    image: 'uhhlt/nlp_thumbnailannotator_app:latest'
    ports:
      - "${APP_PORT}:80"
    
