##
# Example run: 
#  
#  API_PORT=10310 APP_PORT=10311 SERVER="http:\/\/ltdocker:10310" docker-compose up --build -d
#
##
version: '3'

services:
  db:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - ${PWD}/redis-data:/redis

  api:
    depends_on:
      - "db"
    image: 'uhhlt/nlp_thumbnailannotator_api:latest'
    ports:
      - "${API_PORT}:8081"
  app:
    depends_on:
      - "api"
    build: 
      context: ./app
      args:
        - SERVER=${SERVER}
    image: 'uhhlt/nlp_thumbnailannotator_app:latest'
    ports:
      - "${APP_PORT}:80"
    
